tunnel: jdme
credentials-file: /etc/cloudflared/8673c5e6-55c3-457d-9c03-1d84e6127d55.json

ingress:
  - hostname: jdeko.me
    service: http://nginx:80
  - hostname: www.jdeko.me
    service: http://nginx:80
  - service: http_status:404
