services:
  api_jdme:
    build:
      context: .
      dockerfile: new.Dockerfile
    image: api_jdme
    container_name: api_jdme
    ports: 
      - "8080:8080"
    networks:
      jdme_net:
        ipv4_address: 10.7.19.10
      lognet: 
        ipv4_address: 10.0.199.10
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./z_log:/app/z_log
      - ./httplog:/app/httplog
    environment:
      - TZ=America/Chicago
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
# prod is external
  jdme_net: 
    name: jdme_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.19.0/24
          gateway: 10.7.19.1 
  lognet:
    external: true
