services:
  api_jdme:
    build:
      context: .
      dockerfile: Dockerfile
    image: api_jdme
    container_name: api_jdme
    ports: 
      - "8080:8080"
    networks:
      jdme_net:
        ipv4_address: 10.7.19.10
      lognet: 
        ipv4_address: 10.0.199.10
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./z_log:/app/z_log
    environment:
      - TZ=America/Chicago
    healthcheck:
      test: ["CMD", "curl", "-f", "https://jdeko.me/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  jdme_net: 
    external: true
  lognet:
    external: true
