services:
  api_jdme:
    build:
      context: .
      dockerfile: Dockerfile
    image: img_api_jdme
    container_name: api_jdme
    ports:
      - "8080:8080"
    networks:
      jdme_net:
        ipv4_address: 10.7.19.10
      dbnet:
        ipv4_address: 10.0.13.152
    volumes:
      - ./log:/app/log
      - ./:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped

networks:
  jdme_net: 
    external: true

  dbnet:
    external: true
