services:
  api_jdme:
    build:
      context: .
      dockerfile: new.Dockerfile
      # dockerfile: Dockerfile
    image: api_jdme
    container_name: api_jdme
    ports: 
      - "8080:8080"
    networks:
      jdme_net:
        ipv4_address: 10.7.19.10
      # dbnet:
        # 152 for prod, 153 for dev
        # ipv4_address: 10.0.13.153
    volumes:
      # - ./log:/app/log
      # - ./:/app
      - /etc/localtime:/etc/localtime:ro
      - ./z_log:/app/z_log
    environment:
      - TZ=America/Chicago
    healthcheck:
      test: ["CMD", "curl", "-f", "https://jdeko.me/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
# prod is external
  jdme_net: 
    name: jdme_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.19.0/24
          gateway: 10.7.19.1 
  # dbnet:
  #   external: true
