services:
  api_jdme:
    build:
      context: .
      dockerfile: Dockerfile
    image: jdekome_api_dev
    container_name: jdekome_api_dev
    ports: 
      - "8080:8080"
    networks:
      jdme_net:
        ipv4_address: 10.7.19.10
      dbnet:
        ipv4_address: 10.0.13.152
    volumes:
      - ./log:/app/log
      - ./:/app
      - /etc/localtime:/etc/localtime:ro
      - ./z_log:/app/z_log
    restart: unless-stopped

networks:
# prod is external
  jdme_net: 
    external: true
  dbnet:
    external: true