services:
# POSTGRES DATABASE
  postgres:
    container_name: pgbball
    image: jdme-pg
    build: 
      context: db/.
      dockerfile: pg.Dockerfile
    env_file: 
      - ../.env
    networks:
      pgnet:
    ports:
      - "9876:5432"
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-dump:/var/lib/postgresql/dump

# DAILY STATS FETCH
  pgfetch:
    container_name: pgfetch
    depends_on: 
      postgres:
        condition: service_healthy
    image: jdme-pgfetch
    build: 
      context: db/.
      dockerfile: pgfetch/fetch.Dockerfile
    env_file: ../.env
    networks:
      pgnet:
    restart: unless-stopped
    volumes:
      - pg-dump:/dump
      - fetchlog:/app/log 
# MONGO DATABASE
  mongo:
    container_name: mongo
    image: jdme-mongo
    build:
      context: mongo/.
      dockerfile: mongo.Dockerfile
    env_file:
      - ../.env
    networks:
      lognet:
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
      - mongo-conf:/data/configdb

# MONGO EXPRESS UI
  mongox:
    container_name: mongox
    depends_on:
      mongo:
        condition: service_healthy
    image: jdme-mongox
    build:
      context: mongo/.
      dockerfile: mongox.Dockerfile
    env_file:
      - ../.env
    networks:
      lognet:
      apinet:
    ports:
      - "8081:8081"
    restart: unless-stopped
    
# GO API  
  api:
    container_name: api
    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: jdme-api
    build:
      context: ..
      dockerfile: jdme-dkr/api.Dockerfile
    env_file:
      - ../.env
    networks:
      apinet:
      lognet: 
      pgnet:
    ports: 
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - applog:/app/z_log/app
      - applog_dbg:/app/z_log/dbg
      - appdata:/app/persist

# REVERSE PROXY
  nginx:
    container_name: nginx
    build:
      context: nginx/.
      dockerfile: nginx.Dockerfile
    image: jdme-nginx
    depends_on:
      api:
        condition: service_healthy
      mongox:
        condition: service_healthy
    ports:
      - "80:80"
    networks:
      apinet:
      lognet:
      cfnet:
    restart: unless-stopped
    volumes:
      - proxylog:/var/log/nginx
      - www:/var/www
      - cvpublic:/var/hugocv

  cloudflared:
    container_name: cf
    build:
      context: cloudflare/.
      dockerfile: cf.Dockerfile
    env_file:
      - ../.env
    image: jdme-cloudflared
    restart: unless-stopped
    # command: tunnel run jdme
    command: tunnel --config /etc/cloudflared/config.yml run
    networks:
      cfnet:

  # nfstst:
  #   container_name: nfstst
  #   image: alpine
  #   volumes:
  #     - tst:/ts
  #   command: sh -c "ls -la /ts && sleep infinity"

# NETWORKS
networks:
  apinet: 
    name: apinet
    driver: bridge

  lognet:
    name: lognet
    driver: bridge

  pgnet:
    name: pgnet
    driver: bridge

  cfnet:
    name: cfnet
    driver: bridge

# VOLUMES
volumes:
  pg-data:
    name: pg-data
  pg-dump:
    name: pg-dump   
  fetchlog:
    name: fetchlog
  mongo-data:
    name: mongo-data
  mongo-conf:
    name: mongo-conf
  applog:
    name: applog
  applog_dbg:
    name: applog_dbg
  appdata: 
    name: appdata
  app_static:
    name: app_static
  proxylog:
    name: proxylog
  www:
    name: www
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../www
  cvpublic: 
    name: cvpublic
  cvsrc:
    name: cvsrc

  # tst:
  #   driver: local
  #   name: tst
  #   driver_opts:
  #     type: nfs
  #     o: addr=100.107.48.54,nolock,soft,rw
  #     device: ":/mnt/dekonet/jdme/logs"   