services:
# POSTGRES DATABASE
  postgres:
    container_name: pgbball
    image: jdme-pg
    build: 
      context: db/.
      dockerfile: pg.Dockerfile
    env_file: 
      - ../.env
    networks:
      pgnet:
    ports:
      - "8765:5432"
    restart: unless-stopped
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-dump:/var/lib/postgresql/dump

# DAILY STATS FETCH
  pgfetch:
    container_name: pgfetch
    depends_on: 
      postgres:
        condition: service_healthy
    image: jdme-pgfetch
    build: 
      context: db/.
      dockerfile: pgfetch/fetch.Dockerfile
    env_file: ../.env
    networks:
      pgnet:
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # - pg-dump:/dump

# DAILY PG DUMP
  pgbkp:
    container_name: pgbkp
    depends_on: 
      postgres:
        condition: service_healthy
    image: jdme-pgbkp
    build: 
      context: db/.
      dockerfile: pgbkp/bkp.Dockerfile
    env_file: ../.env
    networks:
      pgnet:
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pg-dump:/dump
    
# MONGO DATABASE
  mongo:
    container_name: mongo
    image: mongo
    build:
      context: mongo/.
      dockerfile: mongo.Dockerfile
    env_file:
      - ../.env
    networks:
      lognet:
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db

# MONGO EXPRESS UI
  mongox:
    container_name: mongox
    depends_on:
      mongo:
        condition: service_healthy
    image: mongox
    build:
      context: mongo/.
      dockerfile: mongox.Dockerfile
    env_file:
      - ../.env
    networks:
      lognet:
      apinet:
    ports:
      - "8081:8081"
    restart: unless-stopped
    
# GO API  
  api:
    container_name: api
    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: jdme-api
    build:
      context: ..
      dockerfile: jdme-dkr/api.Dockerfile
    env_file:
      - ../.env
    networks:
      apinet:
      lognet: 
      pgnet:
    ports: 
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - applog:/app/z_log/app
      - applog_dbg:/app/z_log/dbg
      - appdata:/app/persist
      - app_static:/app/static

# REVERSE PROXY
  nginx:
    container_name: nginx
    build:
      context: proxy/.
      dockerfile: nginx.Dockerfile
    image: jdme-nginx
    depends_on:
      api:
        condition: service_started
      mongox:
        condition: service_started
    ports:
      - "80:80"
    networks:
      apinet:
      lognet:
    restart: always

networks:
  apinet: 
    name: apinet
    driver: bridge

  lognet:
    name: lognet
    driver: bridge

  pgnet:
    name: pgnet
    driver: bridge

volumes:
  pg-data:
    name: pg-data
  pg-dump:
    name: pg-dump
  mongo-data:
    name: mongo-data
  applog:
    name: applog
  applog_dbg:
    name: applog_dbg
  appdata: 
    name: appdata
  app_static:
    name: app_static