services:
# POSTGRES DATABASE
  postgres:
    container_name: pgbball
    image: jdme-pg
    build: 
      context: .
      dockerfile: pg.Dockerfile
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-dump:/var/lib/postgresql/dump
    networks:
      pgnet:
    ports:
      - "8765:5432"
    env_file: 
      - ../.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    

  # MONGO DATABASE
  mongo:
    container_name: mongo
    image: mongo
    build:
      context: .
      dockerfile: mongo.Dockerfile
    restart: always
    env_file:
      - ../.env
    networks:
      lognet:
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # MONGO EXPRESS UI
  mongox:
    image: mongo-express
    container_name: mongox
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - ../.env
    networks:
      lognet:
      apinet:
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mongox:8081/status"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    
  # GO API  
  api:
    container_name: api
    depends_on:
      mongo:
        condition: service_healthy
      postgres:
        condition: service_healthy
    build:
      context: ..
      dockerfile: dkr-jdme/api.Dockerfile
    image: jdme-api
    restart: unless-stopped
    env_file:
      - ../.env
      # - TZ=America/Chicago
    networks:
      apinet:
      lognet: 
      pgnet:
    ports: 
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../z_log:/app/z_log
      - ../persist:/app/persist
    healthcheck:
      test: ["CMD", "curl", "-f", "http://api:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 15s

# REVERSE PROXY
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: jdme-nginx
    depends_on:
      api:
        condition: service_started
      mongox:
        condition: service_started
    ports:
      - "80:80"
    networks:
      apinet:
      lognet:
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/proxy-health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

# 
networks:
  apinet: 
    name: apinet
    driver: bridge

  lognet:
    name: lognet
    driver: bridge

  pgnet:
    name: pgnet
    driver: bridge

volumes:
  pg-data:
    name: pg-data
  pg-dump:
    name: pg-dump
  mongo-data:
    name: mongo-data
    # driver_opts:
    #   type: "nfs"
    #   o: "addr=100.107.48.54,nolock,soft,rw"
    #   device: "/mnt/dekonet/jdme"

