services:
  apache_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache_proxy_jdme
    container_name: jdme_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      jdme_net:
        ipv4_address: 10.7.19.211
    restart: unless-stopped
  
networks:
  jdme_net:
    name: jdme_net
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.19.0/24
          gateway: 10.7.19.1