tunnel: jdme
credentials-file: /etc/cloudflared/2fa7d121-ba14-4528-b372-a9b508c37797.json

ingress:
  - hostname: jdeko.me
    service: http://nginx:80
  - hostname: www.jdeko.me
    service: http://nginx:80
  - service: http_status:404
