services:
  mongo:
    image: mongo
    container_name: jdme_mongo
    restart: always
    env_file:
      - ../.env
    environment:
      - TZ=America/Chicago
    networks:
      lognet:
        ipv4_address: 10.0.199.199
    ports:
      - "27017:27017"

networks:
  lognet:
    name: lognet
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.199.0/24
          gateway: 10.0.199.1