# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SRV_IP: ${{ secrets.SRV_IP }}
      MONGO_HOST: ${{ secrets.MONGO_HOST }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}
      MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      MONGO_INITDB_DATABASE: ${{ secrets.MONGO_INITDB_DATABASE }}
      PG_HOST: ${{ secrets.PG_HOST }}
      PG_USER: ${{ secrets.PG_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      PG_PASS: ${{ secrets.POSTGRES_PASSWORD }}
      PG_DB: ${{ secrets.POSTGRES_DB }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Debug env
      run : |
        echo "MONGO_HOST=$MONGO_HOST"
        echo "PG_HOST=$PG_HOST"
        echo "PG_PORT=$PG_PORT"
        echo "PG_USER=$PG_USER"
        echo "PG_PASS=$PG_PASS"
        echo "PG_DB=$PG_DB"

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'

    - name: Build
      run: go build -o bin/app ./main

    - name: Test
      run: go test ./main